// site routes will be here
export const routes = {
  admin: {
    dashboard: "/admin/dashboard",
    riders: "/admin/riders",
    registerRider: "/admin/riders/register",
    riderDetail: "/admin/riders/detail",
    riderHistory: "/admin/riders/history",
    deliveryCompany: "/admin/logistics-company",
    registerDeliveryCompany: "/admin/logistics-company/register",
    deliveryCompanyDetail: "/admin/logistics-company/detail",
    retailCompany: "/admin/retail-company",
    registerRetailCompany: "/admin/retail-company/register",
    retailCompanyOrderSummary: "/admin/retail-company/order-summary",
    retailCompanyDetail: "/admin/retail-company/detail",
    customer: "/admin/direct-customer",
    registerCustomer: "/admin/direct-customer/register",
    customerDetail: "/admin/direct-customer/detail",
    orders: "/admin/orders",
    createOrder: "/admin/orders/order-now",
    orderSummary: "/admin/orders/order-summary",
    orderHistory: "/admin/order-history",
    earning: "/admin/earning",
    transaction: "/admin/transaction",
    collectionCenter: "/admin/collection-center",
    addCollectionCenter: "/admin/collection-center/add",
    subscription: "/admin/subscription",
    addSubscription: "/admin/subscription/add",
    deliveryPlan: "/admin/delivery/all",
    addDeliveryPlan: "/admin/delivery/add",
    editDeliveryPlan: "/admin/delivery/edit",
    report: "/admin/report",
    setting: "/admin/setting",
    coupon: "/admin/coupon/all",
    addCoupon: "/admin/coupon/add",
    markup: "/admin/markup/all",
    addMarkup: "/admin/markup/add",
    staff: "/admin/staff/all",
    addStaff: "/admin/staff/add",
    support: "/admin/support",
  },
  auth: {
    login: "/",
    sign: "/signup",
    confirm: "/signup/confirm",
    vertify: "/vertify",
    forgot: "/forgot",
    new: "/new",
    recovery: "/recovery",
  },
  company: {
    confirm: "/company/confirm",
    recovery: "/company/recovery",
    signin: "/company/signin",
    createPassword: "/company/new",
    vertify: "/company/vertify",
    dashboard: "/company-admin/dashboard",
    riders: "/company-admin/riders",
    orders: "/company-admin/orders",
    orderHistory: "/company-admin/order-history",
    earning: "/company-admin/earning",
    report: "/company-admin/report",
    setting: "/company-admin/setting",
    support: "/company-admin/support",
    riderDetail: "/company-admin/riders/detail",
    internalSummary: "/company-admin/orders/in-summary",
  },
};
